services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_php
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    volumes:
      - ./src:/var/www/html/src/

  nginx:
    image: nginx:alpine
    container_name: telegram_bot_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql