services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_php
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    volumes:
      - ./src:/var/www/html/src/

  nginx:
    image: nginx:alpine
    container_name: telegram_bot_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf